don't exit with error code in post-deploy

diff --git a/.kamal/hooks/post-deploy b/.kamal/hooks/post-deploy
--- a/.kamal/hooks/post-deploy
+++ b/.kamal/hooks/post-deploy
@@ -15,7 +15,16 @@ if ! command -v pg_isready &> /dev/null; then
         echo "This script must be run as root to install pg_isready."
         exit 1
     fi
+    
     apt-get update && apt-get install -y postgresql-client
+    
+    if ! command -v pg_isready &> /dev/null; then
+        echo "pg_isready installation failed. Exiting."
+        exit 0 
+        # Do not exit with error code here 
+        # since DB is already working, 
+        # else app wouldnt be running
+    fi
 fi
 
 until pg_isready -h "${DB_HOST}" -p "${DB_PORT}" -d "tramline_staging" -U "postgres" | grep -q "accepting connections"; do
