update

diff --git a/.github/workflows/deploy-staging-gcp.yml b/.github/workflows/deploy-staging-gcp.yml
--- a/.github/workflows/deploy-staging-gcp.yml
+++ b/.github/workflows/deploy-staging-gcp.yml
@@ -71,22 +71,17 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_STAGING_GCP }}
 
-      - name: Test SSH connection to VM
-        run: |
-          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p 2222 sam-staging-local@$SERVER_ADDR "exit"
-          echo "SSH connection successful"
-
       - name: Disable Git safe directory check
         run: git config --global --add safe.directory '*'
 
-      - name: Debug Docker Login
-        run: |
-          echo "Testing direct Docker login..."
-          docker login ghcr.io -u $KAMAL_REGISTRY_USERNAME -p $KAMAL_REGISTRY_PASSWORD
-          echo "Docker login exit status: $?"
-        env:
-          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD_STAGING_GCP }}
-          KAMAL_REGISTRY_USERNAME: tramlinehq
+      # - name: Debug Docker Login
+      #   run: |
+      #     echo "Testing direct Docker login..."
+      #     docker login ghcr.io -u $KAMAL_REGISTRY_USERNAME -p $KAMAL_REGISTRY_PASSWORD
+      #     echo "Docker login exit status: $?"
+      #   env:
+      #     KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD_STAGING_GCP }}
+      #     KAMAL_REGISTRY_USERNAME: tramlinehq
 
       - name: Login to registry
         run: kamal registry login
